"""Build a deterministic single-file Kaggle submission.

The generated file embeds the current ``ow_sim``, ``ow_planner``, and
``agents`` modules and exposes ``agent`` at top level. It intentionally avoids
tests, docs, scripts, caches, and non-stdlib build dependencies.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
BUNDLE_PACKAGES = ("ow_sim", "ow_planner", "agents")


@dataclass(frozen=True, slots=True)
class BundledModule:
    """Source module metadata for the submission bundle."""

    module_name: str
    relative_path: str
    is_package: bool
    source: str


def discover_bundle_modules(
    repo_root: Path | str = REPO_ROOT,
    packages: Sequence[str] = BUNDLE_PACKAGES,
) -> tuple[BundledModule, ...]:
    """Return bundled source modules in deterministic path order."""

    root = Path(repo_root)
    modules: list[BundledModule] = []
    for package in packages:
        package_root = root / package
        if not package_root.is_dir():
            raise ValueError(f"missing package directory: {package}")

        for path in sorted(package_root.rglob("*.py")):
            relative_path = path.relative_to(root).as_posix()
            module_name = _module_name_from_relative_path(relative_path)
            modules.append(
                BundledModule(
                    module_name=module_name,
                    relative_path=relative_path,
                    is_package=path.name == "__init__.py",
                    source=path.read_text(encoding="utf-8"),
                )
            )

    return tuple(modules)


def build_submission_source(repo_root: Path | str = REPO_ROOT) -> str:
    """Build deterministic Python source for a standalone submission file."""

    modules = discover_bundle_modules(repo_root)
    sources = {
        module.module_name: module.source
        for module in modules
    }
    package_names = tuple(
        module.module_name
        for module in modules
        if module.is_package
    )

    lines = [
        "# Generated by scripts/build_submission.py. Do not edit.",
        "from __future__ import annotations",
        "",
        "import importlib",
        "import importlib.abc",
        "import importlib.util",
        "import sys",
        "",
        "_BUNDLED_SOURCES = {",
    ]
    for module_name in sorted(sources):
        lines.append(f"    {module_name!r}: {sources[module_name]!r},")
    lines.extend(
        [
            "}",
            f"_BUNDLED_PACKAGES = frozenset({package_names!r})",
            "",
            "",
            "class _BundledLoader(importlib.abc.Loader):",
            "    def create_module(self, spec):",
            "        return None",
            "",
            "    def exec_module(self, module):",
            "        module_name = module.__spec__.name",
            "        source = _BUNDLED_SOURCES[module_name]",
            "        module.__file__ = _module_file(module_name)",
            "        module.__loader__ = self",
            "        if module_name in _BUNDLED_PACKAGES:",
            "            module.__package__ = module_name",
            "            module.__path__ = [_module_path(module_name)]",
            "        else:",
            "            module.__package__ = module_name.rpartition('.')[0]",
            "        code = compile(source, module.__file__, 'exec')",
            "        exec(code, module.__dict__)",
            "",
            "",
            "class _BundledFinder(importlib.abc.MetaPathFinder):",
            "    def find_spec(self, fullname, path=None, target=None):",
            "        if fullname not in _BUNDLED_SOURCES:",
            "            return None",
            "        return importlib.util.spec_from_loader(",
            "            fullname,",
            "            _BUNDLED_LOADER,",
            "            is_package=fullname in _BUNDLED_PACKAGES,",
            "        )",
            "",
            "",
            "def _module_file(module_name):",
            "    path = module_name.replace('.', '/')",
            "    if module_name in _BUNDLED_PACKAGES:",
            "        return f'<orbit_wars_submission>/{path}/__init__.py'",
            "    return f'<orbit_wars_submission>/{path}.py'",
            "",
            "",
            "def _module_path(module_name):",
            "    return f\"<orbit_wars_submission>/{module_name.replace('.', '/')}\"",
            "",
            "",
            "_BUNDLED_LOADER = _BundledLoader()",
            "sys.meta_path.insert(0, _BundledFinder())",
            "agent = importlib.import_module('agents.orbit_wars_agent').agent",
            "__all__ = ('agent',)",
            "",
        ]
    )
    return "\n".join(lines)


def write_submission(
    output: Path | str,
    repo_root: Path | str = REPO_ROOT,
) -> Path:
    """Write the deterministic submission file and return its path."""

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_submission_source(repo_root), encoding="utf-8")
    return output_path


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build a single-file Orbit Wars Kaggle submission.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to write the generated submission Python file.",
    )
    args = parser.parse_args(tuple(argv) if argv is not None else None)
    write_submission(args.output)
    return 0


def _module_name_from_relative_path(relative_path: str) -> str:
    parts = relative_path.removesuffix(".py").split("/")
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts)


__all__ = (
    "BUNDLE_PACKAGES",
    "BundledModule",
    "build_submission_source",
    "discover_bundle_modules",
    "main",
    "write_submission",
)


if __name__ == "__main__":
    raise SystemExit(main())
